server:
  port: 8081 #服务端口
spring:
  aop:
    auto: true #默认开启AOP
  #区分开发环境还是测试环境
  #借助Spring的注解@Profile("dev")实现，需要定义两个实现EmailService接口的类
  # dev-开发环境 test-测试环境  prod-生产环境
  profiles:
    active: dev
  #数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/pfm_sd?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  #热部署
  devtools:
    remote:
      restart:
        enabled: true # 开启热部署
  freemarker:
    cache: false #页面不缓存，修改即时生效
  #redis相关配置
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 127.0.0.1 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: "@wecredo2016" # Redis服务器连接密码（默认为空） 带有特殊字符的要用""包起来，要不然found character '@' that cannot start any token. (Do not use @ for indentation)
    jedis:
      pool:
        max-active: 20 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 1000 # 连接超时时间（毫秒）
# mapper存放位置
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.xiufengd.domain
#日志击别
logging:
  level:
    com:
      xiufengd:
        mapper: debug
